"""Stage Checklist Engine — real per-stage entry/exit criteria for the seven
INTK-* intake stages, replacing the unconditional OPBOH-assessment
requirement for stages that have one configured. See
services/stage_engine.py and models/stage_checklist.py's module docstrings
for the full mechanism and its sourcing.

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-16 11:00:34.121650
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0009"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stage_checklist_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("criterion", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stage_checklist_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column(
            "response_value",
            sa.Enum("yes", "no", "not_applicable", name="checklist_response_value"),
            nullable=True,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("answered_by", sa.String(length=36), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["stage_checklist_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stage_checklist_responses_tenant_id"),
        "stage_checklist_responses",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "stage_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "proceed",
                "proceed_with_conditions",
                "return_for_information",
                "require_due_diligence",
                "escalate_for_specialist_review",
                "hold_pending",
                "decline",
                name="stage_decision_outcome",
            ),
            nullable=False,
        ),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=36), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stage_decisions_tenant_id"), "stage_decisions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###
    #
    # NOTE: autogenerate also proposed dropping ~17 indexes on other tables
    # (opboh_*, gate_*, projects, notifications, framework_*,
    # stage_gate_decisions) — a pre-existing mismatch between those FK
    # columns' plain `mapped_column(...)` declarations (no `index=True`) and
    # the actual indexes earlier migrations created for them, unrelated to
    # this change. Deliberately not touched here — reviewed and stripped
    # from this migration by hand rather than silently dropping working
    # indexes as a side effect of an unrelated PR.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stage_decisions_tenant_id"), table_name="stage_decisions")
    op.drop_table("stage_decisions")
    op.drop_index(
        op.f("ix_stage_checklist_responses_tenant_id"), table_name="stage_checklist_responses"
    )
    op.drop_table("stage_checklist_responses")
    op.drop_table("stage_checklist_items")
    # ### end Alembic commands ###
    # Not autogenerated — op.drop_table doesn't drop the enum types it used;
    # same fix 0008 already needed for opboh_response_value.
    sa.Enum(name="stage_decision_outcome").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="checklist_response_value").drop(op.get_bind(), checkfirst=True)
